name: Release Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run npm run download
        run: npm run download

      - name: Upload downloads directory
        uses: actions/upload-artifact@v2
        with:
          path: downloads
          if-no-files-found: error
          if-no-files-found-message: "No files found to upload."
          patterns: |
            *.
            *.exe
